/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
RE-MASTERED: Intro Animation + Waving + Smooth LookAt
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'



export function Eve(props) {
  const group = useRef()
  
  // REF BAGIAN TUBUH
  const headRef = useRef() 
  const leftHandRef = useRef()
  const rightHandRef = useRef()
  const bodyRef = useRef()
  
  const [hovered, setHover] = useState(false)
  const { nodes, materials } = useGLTF('/eve/scene.gltf')

  useFrame((state) => {
    const t = state.clock.getElapsedTime(); // Waktu berjalan (detik)

    // --- FASE 1: INTRO (TERBANG MASUK) 0 - 1.5 Detik ---
    if (t < 1.5) {
        // Posisi awal X = 10 (Kanan Layar), geser ke 0 (Tengah)
        group.current.position.x = THREE.MathUtils.lerp(group.current.position.x, 0, 0.08);
        group.current.rotation.y = -0.5; // Miring dikit pas terbang
    } 
    
    // --- FASE 2: MENYAPA (WAVING) 1.5 - 3.5 Detik ---
    else if (t >= 1.5 && t < 3.5) {
        // Badan tegak lagi
        group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, 0, 0.1);
        
        // Tangan Kiri Melambai Cepat
        if (leftHandRef.current) {
            leftHandRef.current.rotation.z = Math.sin(t * 15) * 0.3; // Kecepatan lambaian
            leftHandRef.current.position.y = 0.5; // Angkat tangan
        }
        
        // Kepala nengok ke depan (senyum sopan)
        if (headRef.current) {
             headRef.current.rotation.y = THREE.MathUtils.lerp(headRef.current.rotation.y, 0, 0.1);
        }
    } 
    
    // --- FASE 3: INTERAKTIF (3.5 Detik ke atas) ---
    else {
        // 1. KEPALA (Nengok Mouse Smooth)
        if (headRef.current) {
            // Kita bagi 2 biar gak patah lehernya
            const targetX = -state.pointer.y * 0.5;
            const targetY = state.pointer.x * 0.5;
            
            headRef.current.rotation.x = THREE.MathUtils.lerp(headRef.current.rotation.x, targetX, 0.1);
            headRef.current.rotation.y = THREE.MathUtils.lerp(headRef.current.rotation.y, targetY, 0.1);
        }

        // 2. TANGAN (Floating Santai / Idle Animation)
        if (leftHandRef.current) {
            // Kembalikan tangan ke bawah pelan-pelan
            leftHandRef.current.position.y = THREE.MathUtils.lerp(leftHandRef.current.position.y, Math.sin(t * 2) * 0.1, 0.05);
            leftHandRef.current.rotation.z = THREE.MathUtils.lerp(leftHandRef.current.rotation.z, 0, 0.1);
        }
        if (rightHandRef.current) {
            rightHandRef.current.position.y = Math.cos(t * 2) * 0.1;
        }

        // 3. BADAN (Bernapas naik turun)
        if (bodyRef.current) {
            bodyRef.current.position.y = Math.sin(t * 1.5) * 0.05;
        }
    }

    // 4. WARNA MATA (Respon Hover)
    const targetColor = new THREE.Color(hovered ? "#ff0055" : "#00f3ff");
    if (materials.Blue_Light) {
        materials.Blue_Light.color.lerp(targetColor, 0.1);
        materials.Blue_Light.emissive = targetColor;
        materials.Blue_Light.emissiveIntensity = hovered ? 2 : 1.2;
    }
  })

  return (
    <group 
        ref={group} 
        {...props} 
        dispose={null}
        position={[10, 0, 0]} // Start dari jauh kanan
        onPointerOver={() => setHover(true)}
        onPointerOut={() => setHover(false)}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.246}>
          <group name="RootNode">
            <group name="Robot_Origin" position={[0, 9.763, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              
              {/* --- GRUP KEPALA (Mata + Mulut + Kepala) --- */}
              <group ref={headRef} position={[0, -0.06, 2.786]}>
                  
                  {/* Mata (Saya luruskan rotasinya di sini) */}
                  <group name="Empty" position={[0, 0, 0]} rotation={[0, 0, 0]}> 
                    <group name="Eyes" position={[0, -0.431, 0.076]}>
                      <mesh geometry={nodes.Eyes_Blue_Light_0.geometry} material={materials.Blue_Light} />
                    </group>
                  </group>

                  {/* Mulut ikut kepala */}
                  <group name="Mouth" position={[0, -0.44, -0.2]} scale={[1, 1, 2.881]}>
                    <mesh geometry={nodes.Mouth_Blue_Light_0.geometry} material={materials.Blue_Light} />
                  </group>

                  {/* Telinga/Headphone */}
                  <group name="Ears" position={[0, 0.06, 0.18]}>
                    <mesh geometry={nodes.Ears_Black_Matt_0.geometry} material={materials.Black_Matt} />
                  </group>

              </group>

              {/* TANGAN KIRI */}
              <group name="Hand_origin" ref={leftHandRef} position={[0.723, 0, 2.015]} rotation={[0, -0.064, 0]}>
                <group name="hANDS" position={[-0.723, 0, -1.963]}>
                  <mesh geometry={nodes.hANDS_White_Glossy_0.geometry} material={materials.White_Glossy} />
                </group>
              </group>

              {/* TANGAN KANAN */}
              <group name="Hand_origin002" ref={rightHandRef} position={[-0.723, 0, 2.015]} rotation={[0, 0.064, -Math.PI]}>
                <group name="hANDS002" position={[-0.723, 0, -1.963]}>
                  <mesh geometry={nodes.hANDS002_White_Glossy_0.geometry} material={materials.White_Glossy} />
                </group>
              </group>

              {/* BADAN */}
              <group name="Robot" ref={bodyRef} position={[0, 0, 0.051]}>
                <mesh geometry={nodes.Robot_White_Glossy_0.geometry} material={materials.White_Glossy} />
                <mesh geometry={nodes.Robot_Blue_Light_0.geometry} material={materials.Blue_Light} />
                <mesh geometry={nodes.Robot_Black_Matt_0.geometry} material={materials.Black_Matt} />
              </group>

            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eve/scene.gltf')